
-- Add new columns for the extended product form
ALTER TABLE public.shop_products
ADD COLUMN IF NOT EXISTS sku text,
ADD COLUMN IF NOT EXISTS tags text[],
ADD COLUMN IF NOT EXISTS country_of_origin text,
ADD COLUMN IF NOT EXISTS highlights text[],
ADD COLUMN IF NOT EXISTS ingredients text[],
ADD COLUMN IF NOT EXISTS feeding_guide jsonb DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS gst_inclusive boolean DEFAULT true,
ADD COLUMN IF NOT EXISTS tax_percentage numeric DEFAULT 0,
ADD COLUMN IF NOT EXISTS dispatch_city text,
ADD COLUMN IF NOT EXISTS handling_time text,
ADD COLUMN IF NOT EXISTS shipping_free boolean DEFAULT true,
ADD COLUMN IF NOT EXISTS shipping_charges numeric DEFAULT 0,
ADD COLUMN IF NOT EXISTS delivery_scope text DEFAULT 'pan_india',
ADD COLUMN IF NOT EXISTS gst_certificate text,
ADD COLUMN IF NOT EXISTS trade_license text,
ADD COLUMN IF NOT EXISTS fssai_certificate text,
ADD COLUMN IF NOT EXISTS brand_authorization text,
ADD COLUMN IF NOT EXISTS expiry_date date,
ADD COLUMN IF NOT EXISTS batch_number text,
ADD COLUMN IF NOT EXISTS storage_instructions text,
ADD COLUMN IF NOT EXISTS return_policy text,
ADD COLUMN IF NOT EXISTS warranty text,
ADD COLUMN IF NOT EXISTS videos text[],
ADD COLUMN IF NOT EXISTS breed_applicable text[],
ADD COLUMN IF NOT EXISTS low_stock_alert boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS unit text DEFAULT 'piece',
ADD COLUMN IF NOT EXISTS is_draft boolean DEFAULT false;
